### PR TITLE
Use PDM & Ruff instead of Poetry+Black+Flake8+isort

### PR DESCRIPTION
**Pull request by justinmayer**
This also pins Pillow to 9.x, since I observed four test failures when running tests on 10.x:

```
========================================================================== short test summary info ==========================================================================
FAILED pelican/plugins/image_process/test_image_process.py::test_all_transforms[image_path0-detail-transform_params10] - assert (320, 31, 792, 721) is None
FAILED pelican/plugins/image_process/test_image_process.py::test_all_transforms[image_path0-smooth_more-transform_params16] - assert (16, 0, 1016, 728) is None
FAILED pelican/plugins/image_process/test_image_process.py::test_all_transforms[image_path1-detail-transform_params10] - assert (319, 65, 740, 716) is None
FAILED pelican/plugins/image_process/test_image_process.py::test_all_transforms[image_path1-smooth_more-transform_params16] - assert (327, 72, 741, 706) is None
```

### CODE REVIEW

**Comment by MinchinWeb** [comment]
I'm not crazy about pinning Pillow back, as most upgrades there seem to be to fix a CVE.

Does this change the testing framework? (I noticed a bunch of pytest plugins look like they're no longer being installed) These failing tests aren't new because of that, are they?

**Comment by justinmayer** [comment]
I also prefer to avoid long-term pins. Think of this pin as a temporary measure until the issue with the failing tests can be sorted out.

Testing framework is unchanged. Which Pytest plugins do you think are no longer being installed? While I modified the linters, as far as I can tell, the list of Pytest-related dependencies has not changed.

I confirmed that the same tests fail in current `main`, without any of the changes in this PR.

**Comment by MinchinWeb** [comment]
> I also prefer to avoid long-term pins. Think of this pin as a temporary measure until the issue with the failing tests can be sorted out.

Ok, let's create an issue for it, so it doesn't get forgotten about.

One issue I've run into previously is that the tests will fail if the generated image from Pillow isn't a bit-perfect match of the previous results. Would you run the "regenerate image" command, check to make sure they visually match, and then re-run the tests with new images?

This doesn't have to hold up this PR, but might be the simplest way to solve these "failing" tests. The code is thus (pulled from the Readme):

``` python
>>> from pelican.plugins.image_process.test_image_process import generate_test_images
>>> generate_test_images()
36 test images generated!
```

> Testing framework is unchanged. Which Pytest plugins do you think are no longer being installed?

Disregard. I was reviewing it on my phone this morning, and the diff view was unclear. Now on the computer, it's easy to see it's staying the same.

Otherwise, it looks good. Feel free to merge!

**Comment by justinmayer** [comment]
I followed the provided instructions, but running `generate_test_images()` did not produce any difference in the resulting image files that I could detect.

I did a few experiments and tracked the problem down to Pillow 10.3.0, which introduced some change that causes those four tests to fail — a problem that is also present with the current Pillow 10.4.0. So I adjusted the pin to expand the range to: `>9.1,<10.3`

I'll merge this for now and create a new issue to track the problem with Pillow 10.3+.

**Pull request merged**
