### PR TITLE
Repackaging for v2.0.0

### PR DESCRIPTION
**Pull request by kdeldycke**
As discussed in #34, this PR re-packages the plugin to follow nes Pelican 4.5.0 conventions.

TODO:
* [x] Re-arrange and merge commits.
* [x] Rename `master` branch to `main`. WIP at https://github.com/pelican-plugins/image-process/issues/35.
* [x] Setup CI/CD by the way of GitHub workflows.
* [x] ~Fix unittests~. We're not going to fix them. I'm working on another PR to both fix them and rewrite them with `pytest` idioms. 

Note: this is a re-opening of the original PR at #36 that was closed following the renaming of the `master` branch to `main`.

### CODE REVIEW

**Comment by justinmayer** [comment]
Not that it matters at this point, but out of curiosity, is it not possible to change the target branch (from `master` to `main`) in the existing PR instead of creating a new one?

**Comment by kdeldycke** [comment]
I just finished addressing all comments. This PR is ready to be merged! Feel free to add a final review.

I'm waiting for this merge to start working on unittests.

**Comment by kdeldycke** [comment]
> is it not possible to change the target branch (from `master` to `main`) in the existing PR instead of creating a new one?

I'm not aware if this is possible or not. I guess if it would then GitHub would not automatically close the PR on renaming... 😬

**Comment by justinmayer** [comment]
Ah, my bad. I had no idea that was what had happened. I imagine one *can* change the target branch, but only before the previously-targeted branch is deleted. 😉

**Review by justinmayer — APPROVED** [review]
Looks good to me. 👍

**Comment by kdeldycke** [comment]
Thanks @justinmayer for the feedback! Let's merge then! 🥳

**Pull request merged**
