### PR TITLE
Add 'link_original' pseudo-transform to link to the original file

### LINKED ISSUE #31: click through to full image
I can see that not every one want to host full size images but i would like users/views of my blog to be able to click through to the original.

Have i missed something in the config or is this much harder to do?

If its do able i would be happy to help but im not sure what the maintainers think is the best way to do this? if a doc fix is what is needed i am happy to help with that or to add some code.. but dont want to duplicate effort if some already knows how to do it

### PR DESCRIPTION
**Pull request by projectgus**
Thanks for this plugin, it makes image management very convenient!

I wanted to link most of my images back to the full-sized source, so I've added `link_original` as a kind of "pseudo-transform" feature. Please let me know if you think this is useful. 

Closes #31

### CODE REVIEW

**Comment by kernc** [comment]
FWIW, that's fairly easy and DRY to achieve in markdown:

```md
[![alt text][img_id]{:.image-process-thumb}][img_id]
...

[img_id]: {static}/images/my_image.jpg
...
```

**Comment by projectgus** [comment]
@kernc Fair enough! I did see that, I think in my case I prefer having everything in one concise line. But I fully appreciate if you prefer to close this and not merge it.

**Comment by projectgus** [comment]
Hmm I don't know why the pre-commit is failing there, but it's a moot point if this is being closed anyway. :).

**Comment by patrickfournier** [comment]
@projectgus Thanks for your PR. However, since it is possible to add links on images both in Markdown and restructuredText, what you are proposing could lead to conflicts (something like `<a href="url-1"> <a href="url-2">  </a> </a>`). I will thus close this PR.

**Pull request closed without merging**
